[package]
name = "chui-trainer"
version = "0.1.0"
edition = "2021"
authors = ["Jonathan Sawyer <jonmsawyer@gmail.com>"]
rust-version = "1.71.0"
categories = ["command-line-utilities", "games", "chess", "training"]
description = "A command line application that allows you train your chess vision by give you problems to solve."
readme = "README.md"
homepage = "https://chui.games/"
repository = "https://github.com/jonmsawyer/chui/tree/main/bin/chui-trainer"
license = "MIT OR Apache-2.0"
keywords = ["chess", "chess trainer", "chui", "chess ui", "chess user interface", "chess command line"]
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chui_core.workspace = true
chui_macros.workspace = true
chui_error.workspace = true
rand = { version = "0.8", features = ["small_rng"] }
