[package]
name = "chui-console"
version = "0.1.1"
edition = "2021"
authors = ["Jonathan Sawyer <jonmsawyer@gmail.com>"]
rust-version = "1.73.0"
categories = ["command-line-utilities", "games", "chess", "training"]
description = "A command line application that allows you play chess with a friend or online."
readme = "README.md"
homepage = "https://chui.games/"
repository = "https://github.com/jonmsawyer/chui/tree/main/crates/chui-console"
license = "MIT OR Apache-2.0"
keywords = ["chess", "chess trainer", "chui", "chess ui", "chess user interface", "chess command line"]
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chui_core.workspace = true
