[package]
name = "chui-dev"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chui_core.workspace = true
# chui_macros.workspace = true
